###############################################################################
# Default                                                                     #
###############################################################################
spring:
  cache:
    type: redis
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    hikari:
#      max-lifetime: 580000
#      register-mbeans: true
#      connectionTestQuery: SELECT 1
#    dbcp2:
#      test-on-borrow: true
#      validation-query: SELECT 1

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

talken:
  dex:
    mam:
      creatorMinBalance: 1000
      channelMinBalance: 1.1
      issuerMinBalance: 2
      netfeeBuffer:
        holder:
          ETH: 0.05
          XLM: 0.005
          LUK: 500
        distributor:
          ETH: 0.1
          XLM: 0.001
          LUK: 1000
    tradeWallet:
      creatorAddress: "GCLTGOKYK7WHPCP6R43FXZZZ7HHUAZJCOQ7H4K6NTQYEUMODYHOLN4XA"
    bcnode:
      stellar:
        network: test
        rpcUri: "http://192.168.0.37:8000"
        publicRpcUri: "https://horizon-testnet.stellar.org"
      ethereum:
        network: test
        rpcUri: "http://192.168.0.37:8545"
        #rpcUri: "http://tn.henesis.io/ethereum/ropsten?clientId=be774503e333c688b2acee1b37de702d"
        gasOracleUrl: "http://192.168.0.37:38084/ethgasAPI.json"
        gasEtherscanUrl: "https://api.etherscan.io/api?module=gastracker&action=gasoracle&apikey=548Q8A315UV37WFIYVDNCS32847ZJVRZ7F"
        infuraUri: "https://ropsten.infura.io/v3/a355d60704c845959bbde06c977819ed"
      luniverse:
        apiUri: "https://api.luniverse.io"
        mainRpcUri: "http://13.125.55.194:8545"
        sideRpcUri: "http://baas-rpc.luniverse.io:8545?lChainId=5300575914426995782"
      klaytn:
        chainId: 1001
        accessKeyId: "KASKSKZAXHOHESP81QUHE2YN"
        secretAccessKey: "Q8UZkFRnpSALo2CHD2/SMCnkum8iiqoayrC/J6W1"
      bsc:
        chainId: 97
        mainRpcUri: "https://data-seed-prebsc-1-s1.binance.org:8545"
      filecoin:
        infuraUri: "https://filecoin.infura.io"
        projectId: "1ld7AhUXVAo1S2dTAFmms9HK7WE"
        projectSecret: "c628cd44465c7d17c8f37afead39106e"
      heco:
        chainId: 256
        mainRpcUri: "https://http-testnet.hecochain.com"


    task:
      createOffer:
        feeRatePivot: 0.005
      deanchor:
        feeAmountTalk: 50
    integration:
      relay:
        apiUrl: http://192.168.0.33:3888/graphql
      wallet:
        apiUrl: http://192.168.0.33:3232/bws
      anchor:
        apiUrl: http://192.168.0.35:3480
      coinMarketCap:
        cryptoCurrencyUrl: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest
        globalMetricUrl: https://pro-api.coinmarketcap.com/v1/global-metrics/quotes/historical

################################################################################
## LOCAL Profile                                                               #
################################################################################
---
spring:
  profiles: local

################################################################################
## DEVELOPMENT Profile                                                         #
################################################################################
---
spring:
  profiles: dev

###############################################################################
# PRODUCTION Profile                                                          #
###############################################################################
---
spring:
  profiles: production
talken:
  dex:
    tradeWallet:
      creatorAddress: "GB2XPIIEXXNXAOUN6SYVKUSEHEDOGHLLXDMQ43KKSVJUKLJO3PWL643F"
    bcnode:
      stellar:
        network: main
        rpcUri: "http://10.27.27.13:8000"
        publicRpcUri: "https://horizon.stellar.org"
      ethereum:
        network: main
        rpcUri: "http://10.27.27.19:8545"
        #rpcUri: "http://tn.henesis.io/ethereum/mainnet?clientId=be774503e333c688b2acee1b37de702d"
        infuraUri: "https://mainnet.infura.io/v3/357ea85d151c49629867ec111c9eccd7"
        gasOracleUrl: "http://10.27.27.13:38084/ethgasAPI.json"
      luniverse:
        apiUri: "https://api.luniverse.io"
        mainRpcUri: "http://13.125.55.194:8545"
        sideRpcUri: "http://baas-rpc.luniverse.io:8545?lChainId=5151520500809142437"
      klaytn:
        chainId: 8217
        accessKeyId: "KASKSKZAXHOHESP81QUHE2YN"
        secretAccessKey: "Q8UZkFRnpSALo2CHD2/SMCnkum8iiqoayrC/J6W1"
      bsc:
        chainId: 56
        mainRpcUri: "https://bsc-dataseed.binance.org"
      filecoin:
        infuraUri: "https://filecoin.infura.io"
        projectId: "1ld7AhUXVAo1S2dTAFmms9HK7WE"
        projectSecret: "c628cd44465c7d17c8f37afead39106e"
      heco:
        chainId: 128
        mainRpcUri: "https://http-mainnet.hecochain.com"
    integration:
      relay:
        apiUrl: http://192.168.0.36:3888/graphql
      wallet:
        apiUrl: http://10.15.144.52:3232/bws
      anchor:
        apiUrl: http://192.168.0.49:3480
      coinMarketCap:
        latestUrl: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest