###############################################################################
# Default                                                                     #
###############################################################################
spring:
  cache:
    type: redis
talken:
  dex:
    mam:
      creatorMinBalance: 1000
      channelMinBalance: 1.1
      issuerMinBalance: 2
      netfeeBuffer:
        holder:
          ETH: 0.05
          XLM: 0.005
          LUK: 500
        distributor:
          ETH: 0.1
          XLM: 0.001
          LUK: 1000
    tradeWallet:
      creatorAddress: "GCLTGOKYK7WHPCP6R43FXZZZ7HHUAZJCOQ7H4K6NTQYEUMODYHOLN4XA"
    bcnode:
      stellar:
        network: test
        rpcUri: "http://192.168.0.37:8000"
      ethereum:
        network: test
        rpcUri: "http://192.168.0.37:8545"
        #rpcUri: "http://tn.henesis.io/ethereum/ropsten?clientId=be774503e333c688b2acee1b37de702d"
        gasOracleUrl: "http://192.168.0.37:38084/ethgasAPI.json"
        infuraUri: "https://ropsten.infura.io/v3/a374b566c26149e2b94cc9bf7bafec50"
      luniverse:
        apiUri: "https://api.luniverse.io"
        mainRpcUri: "http://133.186.197.245:18545"
        sideRpcUri: "http://baas-rpc.luniverse.io:8545?lChainId=5300575914426995782"
    task:
      createOffer:
        feeRatePivot: 0.01
      deanchor:
        feeAmountTalk: 50
    integration:
      relay:
        apiUrl: http://192.168.0.33:3888/graphql
      wallet:
        apiUrl: http://192.168.0.33:3232/bws
      anchor:
        apiUrl: http://192.168.0.35:3480
      coinMarketCap:
        latestUrl: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest

################################################################################
## LOCAL Profile                                                               #
################################################################################
---
spring:
  profiles: local

################################################################################
## DEVELOPMENT Profile                                                         #
################################################################################
---
spring:
  profiles: dev

###############################################################################
# PRODUCTION Profile                                                          #
###############################################################################
---
spring:
  profiles: production
talken:
  dex:
    tradeWallet:
      creatorAddress: "GB2XPIIEXXNXAOUN6SYVKUSEHEDOGHLLXDMQ43KKSVJUKLJO3PWL643F"
    bcnode:
      stellar:
        network: main
        rpcUri: "http://10.27.27.13:8000"
      ethereum:
        network: main
        rpcUri: "http://10.27.27.13:8545"
        infuraUri: "https://mainnet.infura.io/v3/357ea85d151c49629867ec111c9eccd7"
        gasOracleUrl: "http://10.27.27.13:38084/ethgasAPI.json"
      luniverse:
        apiUri: "https://api.luniverse.io"
        mainRpcUri: "http://10.27.27.13:18545"
        sideRpcUri: "http://baas-rpc.luniverse.io:8545?lChainId=5151520500809142437"
    integration:
      relay:
        apiUrl: http://192.168.0.36:3888/graphql
      wallet:
        apiUrl: http://10.15.144.52:3232/bws
      anchor:
        apiUrl: http://192.168.0.49:3480
      coinMarketCap:
        latestUrl: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest