###############################################################################
# Logging Default                                                             #
###############################################################################
logging:
  level:
    io.colligence: DEBUG
    sun.rmi: INFO
    org.springframework: INFO
    org.eclipse.jetty: INFO
    com.zaxxer.hikari: INFO
    org.jooq.tools.LoggerListener: INFO

###############################################################################
# Common Profile                                                              #
###############################################################################
---
spring:
  main:
    allow-bean-definition-overriding: true
  profiles: common
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    initialization-mode: never
  cache:
    type: redis
  data:
    redis:
      repositories:
        enabled: true
  jooq:
    sql-dialect: MariaDB
  devtools:
    livereload:
      enabled: true
talken:
  dex:
    scheduler:
      pool-size: 4
    accessToken:
      token-header: "X-Auth-Token"
    stellar:
      network: test
      serverList:
        - "http://192.168.0.37:8000"
    server:
      rly-address: http://192.168.0.33:3888/graphql
      wlt-address: http://192.168.0.33:3232/bws/api
      txt-address: http://192.168.0.33:3232/bws/api
      txt-server-id: "DEX"
      anc-address: http://192.168.0.35:3480
    fee:
      offerFeeRate: 0.001
      offerFeeRateCtxFactor: 0.5
      deanchorFeePivotAsset: "BTC"
      deanchorFeeAmount: 0.001
      deanchorFeeRateCtxFactor: 0.5
      refundRetryInterval: 600
      refundMaxRetry: 5

###############################################################################
# LOCAL Profile                                                               #
###############################################################################
---
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
vault:
  uri: "http://192.168.0.30:8200"
  app-role: "tkn-dex"
  secret-key: "1234"
#logging:
#  level:
#    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# DEVELOPMENT Profile                                                         #
###############################################################################
---
spring:
  profiles: dev
vault:
  uri: "http://192.168.0.20:8200"
  app-role: "tkn-dex"
  secret-key: "9652fa4b5ad08bd8a5464eb491f7e1e1"
logging:
  level:
    io.colligence: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
###############################################################################
# TEST Profile                                                                #
###############################################################################
#---
#spring:
#  profiles: prod
#  datasource:
#    url: jdbc:mariadb://192.168.0.20:4306/talken_db
#    username: root
#    password: 112233
#    dbcp2:
#      driver-class-name: org.mariadb.jdbc.Driver

###############################################################################
# PRODUCTION Profile                                                          #
###############################################################################
#---
#spring:
#  profiles: prod
#  datasource:
#    url: jdbc:mariadb://192.168.0.20:4306/talken_db
#    username: root
#    password: 112233
#    dbcp2:
#      driver-class-name: org.mariadb.jdbc.Driver

###############################################################################
# Verbose Mode Profile                                                        #
###############################################################################
---
spring:
  profiles: verbose
logging:
  level:
    io.colligence: TRACE
    org.springframework.transaction: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
    org.springframework.security: DEBUG
    com.google.api.client.http: DEBUG