###############################################################################
# Logging Default                                                             #
###############################################################################
logging:
  level:
    io.colligence: DEBUG
    sun.rmi: INFO
    org.springframework: INFO
    org.eclipse.jetty: INFO
    com.zaxxer.hikari: INFO
    org.jooq.tools.LoggerListener: INFO

###############################################################################
# Common Profile                                                              #
###############################################################################
---
spring:
  profiles: common
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    initialization-mode: never
  cache:
    type: redis
  data:
    redis:
      repositories:
        enabled: true
  jooq:
    sql-dialect: MariaDB
  devtools:
    livereload:
      enabled: true
talken:
  dex:
    stellar:
      network: test
      serverList:
        - https://horizon-testnet.stellar.org
    server:
      wlt-address: 192.168.0.33
      wlt-port: 3232
      mas-address: 127.0.0.1
      mas-port: 3232
      txt-address: 192.168.0.33
      txt-port: 3232
      anc-address: 192.168.0.35
      anc-port: 3480
    fee:
      offerFeeRate: 0.001
      offerFeeRateForCTX: 0.0005
      deanchorFeePivotAsset: ETH
      deanchorFeeAmount: 0.01
    masMockUp:
      - code: CTX
        assetIssuer: GDQRXWHXYCIZTBYEWMYRCAN5LCLIYV747IHVKUNBEEZ3EKPTIM77CNJL
        assetBase: GDAH6R7EBLRAWBJDENDYE45RN2DST4A34NNYP2XWZNDOTHA7CQZ37JLE
        assetHolder:
          - 0xE0D89aCfa4832156c08D5781321C6C2196F7D779
        offerFeeHolder: GC3TERVBLRYJ275VMJDNUMQJU2RS7YEEWLVRXUMTEZ45XMB7ZUQD3UAK
        deanchorFeeHolder: GC3TERVBLRYJ275VMJDNUMQJU2RS7YEEWLVRXUMTEZ45XMB7ZUQD3UAK
      - code: ETH
        assetIssuer: GDQRXWHXYCIZTBYEWMYRCAN5LCLIYV747IHVKUNBEEZ3EKPTIM77CNJL
        assetBase: GDAH6R7EBLRAWBJDENDYE45RN2DST4A34NNYP2XWZNDOTHA7CQZ37JLE
        assetHolder:
          - 0x6569ce99459E019a0E9b223BB281abf9bA0d941e
        offerFeeHolder: GC3TERVBLRYJ275VMJDNUMQJU2RS7YEEWLVRXUMTEZ45XMB7ZUQD3UAK
        deanchorFeeHolder: GC3TERVBLRYJ275VMJDNUMQJU2RS7YEEWLVRXUMTEZ45XMB7ZUQD3UAK
      - code: BTC
        assetIssuer: GDQRXWHXYCIZTBYEWMYRCAN5LCLIYV747IHVKUNBEEZ3EKPTIM77CNJL
        assetBase: GDAH6R7EBLRAWBJDENDYE45RN2DST4A34NNYP2XWZNDOTHA7CQZ37JLE
        assetHolder:
          - mhLdpzNk1PxvrT4uwnyGsSWiqruVEXnkTA
        offerFeeHolder: GC3TERVBLRYJ275VMJDNUMQJU2RS7YEEWLVRXUMTEZ45XMB7ZUQD3UAK
        deanchorFeeHolder: GC3TERVBLRYJ275VMJDNUMQJU2RS7YEEWLVRXUMTEZ45XMB7ZUQD3UAK
      - code: XLM
        assetIssuer: GDQRXWHXYCIZTBYEWMYRCAN5LCLIYV747IHVKUNBEEZ3EKPTIM77CNJL
        assetBase: GDAH6R7EBLRAWBJDENDYE45RN2DST4A34NNYP2XWZNDOTHA7CQZ37JLE
        assetHolder:
          - GDAH6R7EBLRAWBJDENDYE45RN2DST4A34NNYP2XWZNDOTHA7CQZ37JLE
        offerFeeHolder: GC3TERVBLRYJ275VMJDNUMQJU2RS7YEEWLVRXUMTEZ45XMB7ZUQD3UAK
        deanchorFeeHolder: GC3TERVBLRYJ275VMJDNUMQJU2RS7YEEWLVRXUMTEZ45XMB7ZUQD3UAK

###############################################################################
# LOCAL Profile                                                               #
###############################################################################
---
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
  redis:
    host: localhost
    port: 6379
  #    password: redispassword
  datasource:
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/talken_db
    username: "root"
    password: "!@coLLiGEnce#$"
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver
#logging:
#  level:
#    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# DEVELOPMENT Profile                                                         #
###############################################################################
---
spring:
  profiles: dev
  redis:
    host: 192.168.0.20
    port: 6379
    #    password: redispassword
  datasource:
    url: jdbc:mariadb://192.168.0.20:4006/talken_db
    username: "ms_user"
    password: "maxscale"
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver
logging:
  level:
    io.colligence: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
###############################################################################
# TEST Profile                                                                #
###############################################################################
#---
#spring:
#  profiles: prod
#  datasource:
#    url: jdbc:mariadb://192.168.0.20:4306/talken_db
#    username: root
#    password: 112233
#    dbcp2:
#      driver-class-name: org.mariadb.jdbc.Driver

###############################################################################
# PRODUCTION Profile                                                          #
###############################################################################
#---
#spring:
#  profiles: prod
#  datasource:
#    url: jdbc:mariadb://192.168.0.20:4306/talken_db
#    username: root
#    password: 112233
#    dbcp2:
#      driver-class-name: org.mariadb.jdbc.Driver

###############################################################################
# Verbose Mode Profile                                                        #
###############################################################################
---
spring:
  profiles: verbose
logging:
  level:
    io.colligence: TRACE
    org.springframework.transaction: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
    org.springframework.security: DEBUG
    com.google.api.client.http: DEBUG