package io.talken.dex.shared.exception;

import io.talken.common.exception.TalkenException;

public enum DexExceptionTypeEnum implements TalkenException.ExceptionTypeEnum {
	INTERNAL_SERVER_ERROR(0),
	UNAUTHORIZED(1),
	PARAMETER_VIOLATION(2),
	TASK_NOT_FOUND(3),
	STELLAR_EXCEPTION(4),
	TASK_INTEGRITY_CHECK_FAILED(6),
	ACCOUNT_NOT_FOUND(7),
	TX_HASH_NOT_MATCH(8),
	TRANSACTION_RESULT_PROCESSING_ERROR(9),
	SIGNATURE_VERIFICATION_FAILED(10),
	ASSET_CONVERT_ERROR(11),
	BALANCE_NOT_ENOUGH(12),
	BCTX_EXCEPTION(13),
	EFFECTIVE_AMOUNT_NEGATIVE(14),
	TRADE_WALLET_CREATE_FAILED(19),
	TRADE_WALLET_REBALANCE_FAILED(20),
	DUPLICATED_TASK_FOUND(21),
	OFFER_NOT_VALID(22),
	OWNERSHIP_MISMATCH(23),
	PRIVATE_WALLET_NOT_FOUND(24),
	PENDING_LAST_REQUEST(25),

	// FROM MAS
	CANNOT_UPDATE_HOLDER_STATUS(51),
	ACTIVE_ASSET_HOLDER_NOT_FOUND(52),
	SIGNING_ERROR(53),
	CANNOT_LOAD_TOKEN_META_DATA(54),
	BLOCKCHAIN_PLATFORM_NOT_SUPPORTED(55),

	// STAKING
    STAKING_EVENT_NOT_FOUND(100),
    STAKING_AMOUNT_ENOUGH(101),
    STAKING_USER_ENOUGH(102),
    STAKING_ALREADY_EXISTS(103),
    UNSTAKING_AFTER_STAKING(104),
    UNSTAKING_BEFORE_EXPIRE(105),
    STAKING_BEFORE_START(106),
    STAKING_AFTER_END(107),
    STAKING_BALANCE_NOT_ENOUGH(108),
    STAKING_TOO_LITTLE_AMOUNT(109),
    STAKING_TOO_MUCH_AMOUNT(110),
    STAKING_TOO_OVER_AMOUNT(111),
    UNSTAKING_DISABLED(112),
    UNSTAKING_TOO_OVER_AMOUNT(113);

	private final int code;

	DexExceptionTypeEnum(int code) {
		this.code = code;
	}


	@Override
	public TalkenException.Module getModule() {
		return TalkenException.Module.DEX;
	}

	@Override
	public int getCode() {
		return code;
	}

	@Override
	public String getName() {
		return name();
	}
}
