spring.profiles.include: ['common', 'shared']
###############################################################################
# Default                                                                     #
###############################################################################
spring:
  profiles:
    active: common
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    version: api-1.5.6

talken:
  dex:
    accessToken:
      token-header: "X-Auth-Token"

###############################################################################
# LOCAL Profile                                                               #
###############################################################################
---
spring:
  profiles: local
server:
  port: 8081
vault:
  uri: "http://192.168.0.20:8200"
  app-role: "tkn-dex-api"
  secret-key: "9652fa4b5ad08bd8a5464eb491f7e1e1"
logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# DEVELOPMENT Profile                                                         #
###############################################################################
---
spring:
  profiles: dev
vault:
  uri: "http://192.168.0.20:8200"
  app-role: "tkn-dex-api"
  secret-key: "9652fa4b5ad08bd8a5464eb491f7e1e1"
logging:
  level:
    io.colligence: INFO
    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# PRODUCTION Profile                                                          #
###############################################################################
---
spring:
  profiles: production
vault:
  uri: "http://10.27.27.11:8200"
  app-role: "tkn-dex-api"
  secret-key: ""
talken:
  dex:
    integration:
      wallet:
        apiUrl: http://192.168.0.35:3232/bws