spring.profiles.include: ['common', 'shared']
###############################################################################
# Default                                                                     #
###############################################################################
spring:
  profiles:
    active: common
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
talken:
  dex-api:
    accessToken:
      token-header: "X-Auth-Token"
    server:
      rly-address: http://192.168.0.33:3888/graphql
      wlt-address: http://192.168.0.33:3232/bws/api
      txt-address: http://192.168.0.33:3232/bws/api
      txt-server-id: "DEX"
      anc-address: http://192.168.0.35:3480
    fee:
      offerFeeRate: 0.001
      offerFeeRateCtxFactor: 0.5
      deanchorFeePivotAsset: "BTC"
      deanchorFeeAmount: 0.001
      deanchorFeeRateCtxFactor: 0.5
      refundRetryInterval: 600
      refundMaxRetry: 5

###############################################################################
# LOCAL Profile                                                               #
###############################################################################
---
spring:
  profiles: local
vault:
  uri: "http://192.168.0.30:8200"
  app-role: "tkn-dex-api"
  secret-key: "1234"
#logging:
#  level:
#    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# DEVELOPMENT Profile                                                         #
###############################################################################
---
spring:
  profiles: dev
vault:
  uri: "http://192.168.0.20:8200"
  app-role: "tkn-dex-api"
  secret-key: "9652fa4b5ad08bd8a5464eb491f7e1e1"
#logging:
#  level:
#    io.colligence: DEBUG
#    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# PRODUCTION Profile                                                          #
###############################################################################
---
spring:
  profiles: production
vault:
  uri: "http://10.27.27.11:8200"
  app-role: "tkn-dex-api"
  secret-key: "EaGofP7DnxGeTnL0d0cbC8RiLwpuqwb8U2E5aPNy5y9BZcNfYwSHS2R8LkfjAmSn"
talken:
  dex-api:
    server:
      rly-address: http://192.168.0.36:3888/graphql
      wlt-address: http://192.168.0.35:3232/bws/api
      txt-server-id: "DEX"
      anc-address: http://192.168.0.49:3480