spring.profiles.include: ['common', 'shared']
###############################################################################
# Default                                                                     #
###############################################################################
spring:
  profiles:
    active: common
  application:
    name: TKN-DEX-GOV
  main:
    web-application-type: none
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    hikari:
      max-lifetime: 580000
      maximum-pool-size: 8
      register-mbeans: true
      connectionTestQuery: SELECT 1
      pool-name: HikariPool_DexGOV
      driver-class-name: 'org.mariadb.jdbc.Driver'
      data-source-properties:
        prepStmtCacheSize: '256'
        prepStmtCacheSqlLimit: '2048'
        cachePrepStmts: 'true'
        useServerPrepStmts: 'true'

talken:
  dex:
    scheduler:
      pool-size: 4
      max-pool-size: 16
      queue-capacity: 64

###############################################################################
# LOCAL Profile                                                               #
###############################################################################
---
spring:
  profiles: local
vault:
  uri: "http://192.168.0.30:8200"
  app-role: "tkn-dex-gov"
  secret-key: "1234"
#logging:
#  level:
#    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# DEVELOPMENT Profile                                                         #
###############################################################################
---
spring:
  profiles: dev
vault:
  uri: "http://192.168.0.20:8200"
  app-role: "tkn-dex-gov"
  secret-key: "9652fa4b5ad08bd8a5464eb491f7e1e1"
#logging:
#  level:
#    io.colligence: DEBUG
#    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# PRODUCTION Profile                                                          #
###############################################################################
---
spring:
  profiles: production
vault:
  uri: "http://10.27.27.11:8200"
  app-role: "tkn-dex-gov"
  secret-key: ""