spring.profiles.include: ['common', 'shared']
###############################################################################
# Default                                                                     #
###############################################################################
spring:
  profiles:
    active: common
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
talken:
  dex:
    talkDistributorAddress: "0x633249D02e5695aD2370Ea4B68574689Da84f456"
    scheduler:
      pool-size: 4
      max-pool-size: 16
      queue-capacity: 64
    task:
      swap:
        workerChannel:
          PathPayment:
            publicKey: GADDZIHCLP45NVT3QN2JMMLPNKYRM2EWVPNPBMOIIMIUA2VOZCANFGXP
            secretKey: SCXHZZZPUWNC7AYXVJRJVGKYLMRMLCDSKIJK67J4EAC6LNZDMWMUR4IB
          Deanchor:
            publicKey: GAIMU4NBHKD3F3FXGQCPMMKP7ZRNDVOKJQYDHVX3R6Y4GVD7DXYLZCWD
            secretKey: SAOGUJ3PI64XBYAXBESAP6XCC3BT6XCOLJL3TM2EQAXIVP4X4CI5OAQ6
          FeeCollect:
            publicKey: GDPTY5R5ACTNOTXT5GGU76J6PSVAADHL54PZDCSSIHWUJLPHETDA6QJS
            secretKey: SA5EKYBX4APVLX7JR34RHHTZM2VNKJ4JFVX4NSGVPBHVLWU7SQXUTKFV
          Refund:
            publicKey: GAEDA7A5LN6AOZZTPTG66UOJQ4BLAUDRZ7IYIUDZTG3NE5KSYTBAWG2U
            secretKey: SD6E6B5RTXITG6GUSAIIWYRVFFARCHRZZFDZRIAFRVNTW6J7FEHIY7DA


###############################################################################
# LOCAL Profile                                                               #
###############################################################################
---
spring:
  profiles: local
vault:
  uri: "http://192.168.0.30:8200"
  app-role: "tkn-dex-gov"
  secret-key: "1234"
#logging:
#  level:
#    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# DEVELOPMENT Profile                                                         #
###############################################################################
---
spring:
  profiles: dev
vault:
  uri: "http://192.168.0.20:8200"
  app-role: "tkn-dex-gov"
  secret-key: "9652fa4b5ad08bd8a5464eb491f7e1e1"
#logging:
#  level:
#    io.colligence: DEBUG
#    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# PRODUCTION Profile                                                          #
###############################################################################
---
spring:
  profiles: production
vault:
  uri: "http://10.27.27.11:8200"
  app-role: "tkn-dex-gov"
  secret-key: ""
talken:
  dex:
    talkDistributorAddress: "0x8526E732F405c742d4a078293DaD3a6633b57C79"