spring.profiles.include: ['common', 'shared']
###############################################################################
# Default                                                                     #
###############################################################################
spring:
  profiles:
    active: common
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
talken:
  dex:
    rewardDistributorAddress: "0x633249D02e5695aD2370Ea4B68574689Da84f456"
    integration:
      wallet:
        apiUrl: http://192.168.0.33:3232/bws
      coinMarketCap:
        latestUrl: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest
    scheduler:
      pool-size: 4

###############################################################################
# LOCAL Profile                                                               #
###############################################################################
---
spring:
  profiles: local
vault:
  uri: "http://192.168.0.30:8200"
  app-role: "tkn-dex-gov"
  secret-key: "1234"
#logging:
#  level:
#    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# DEVELOPMENT Profile                                                         #
###############################################################################
---
spring:
  profiles: dev
vault:
  uri: "http://192.168.0.20:8200"
  app-role: "tkn-dex-gov"
  secret-key: "9652fa4b5ad08bd8a5464eb491f7e1e1"
#logging:
#  level:
#    io.colligence: DEBUG
#    org.jooq.tools.LoggerListener: DEBUG

###############################################################################
# PRODUCTION Profile                                                          #
###############################################################################
---
spring:
  profiles: production
vault:
  uri: "http://10.27.27.11:8200"
  app-role: "tkn-dex-gov"
  secret-key: ""
talken:
  dex:
    rewardDistributorAddress: "0x8526E732F405c742d4a078293DaD3a6633b57C79"
    integration:
      wallet:
        apiUrl: http://192.168.0.33:3232/bws
      coinMarketCap:
        latestUrl: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest